### ISSUE TITLE
How do I use it

### ISSUE THREAD

**Issue by xiaole992** [DataGoblin/dayz-server-fake-players#2]

**Comment by vaesanti** [comment]
how to use it?

**Comment by BigDrip420** [comment]
Yeah, how to use it? haha

**Comment by DataGoblin** [comment]
The current opcode likely does not work anymore. Checkout this reply https://github.com/DataGoblin/dayz-server-fake-players/issues/3#issuecomment-2435653257

Have some fun experimenting and you should easily find it after some trial and error.
